source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

gem "rails", "~> 7.0.3"

gem "sprockets-rails"

group :development, :test do
  gem 'sqlite3'
end

group :production do
   gem 'pg'
end

gem 'httparty'

gem 'bcrypt', '~> 3.1.7'

gem "puma", "~> 5.0"

gem "importmap-rails"

gem "turbo-rails"

gem "stimulus-rails"

gem "jbuilder"

gem 'bootstrap', '~> 5.2.0'
gem 'jquery-rails'
gem 'mini_racer'

gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

gem "bootsnap", require: false

gem 'sucker_punch', '~> 3.0'

group :development, :test do
  gem 'pry-byebug'
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  gem "web-console"
  gem 'rack-mini-profiler'
end

group :test do
  gem 'rspec-rails', '~> 6.0.0.rc1'
  gem 'factory_bot_rails'
  gem "capybara"
  gem 'webdrivers', '~> 3.7', '>= 3.7.2'
  gem 'capybara-selenium', '~> 0.0.6'
  gem 'simplecov', require: false
  gem 'webmock'
end
