POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpQGlraS5maSIsImlkIjoyLCJpYXQiOjE2MzQyMzQ1ODV9.L5y6OUqdzhQMq3XSvFsw8zJ72lHfe595sLPKUcoijj0

{
  "author": "Robert C. Martin",
  "title": "Moar on types",
  "url": "https://blog.cleancoder.com/uncle-bob/2021/06/25/OnTypes.html",
  "likes": 1,
  "year": 1900
}