name: Healthcheck

on:
  schedule:
    - cron: '12 * * * *'

jobs:
  ping_the_app:
    runs-on: ubuntu-18.04
    steps:
      - name: Pokedex healthcheck
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://calm-wildwood-40210.herokuapp.com/health
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
